skin_names = ["Human | Default",
              "Human | Tube",
              "Human | DeathAngle",
              "Human | Airstream",
              "Human | CWS",
              "Human | Chris",
              "Human | Red Laser",
              "Human | Deathclaw",
              "Human | Foil",
              "Human | Trident",
              "Human | Apple",
              "Human | Goblin",
              "Human | Ghost",
              "Human | Obat",
              "Human | Vigilantee",
              "Human | St0rm",
              "Human | Cruiser",
              "Human | CT Knife",
              "Alien | Jellyfish",
              "Alien | Frisbee",
              "Alien | Squid",
              "Alien | Retina",
              "Alien | Spikeball",
              "Alien | RadioactiveDonut",
              "Alien | H0T R0D",
              "Alien | FayerBall",
              "Alien | Sonic",
              "Alien | Bow",
              "Alien | RocketShip",
              "Alien | Flash",
              "Alien | Spider",
              "Alien | Arrowhead",
              "Alien | Flex",
              "Alien | Lightning",
              "Alien | Batwing",
              "Alien | T Knife"]
